spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=antiquarian
      username: postgres
      password: postgres
      validation-query: select 1
      test-on-borrow: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: antiquarian
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database: postgresql